In [2]:
import numpy as np

In [3]:
b = np.array([1, 1.5, 2])
print(b)
print(b.dtype)

[ 1.   1.5  2. ]
float64


In [4]:
c = np.array([1 + 2j, 3 + 4j, 5+ 6j])
print(c)
print(c.dtype)

[ 1.+2.j  3.+4.j  5.+6.j]
complex128


In [5]:
f = np.array([100, 200, 300], dtype=np.int16)
print(f)
print(f.dtype)

[100 200 300]
int16


In [6]:
g = np.array([1.5,2.5,3.5])
print(g.dtype)

float64


In [9]:
f = g.astype(np.int64)
print(f)

[1 2 3]


In [10]:
a = np.arange(20)
print(a)

b = np.arange(1,21)
print(b)

c = np.arange(2, 41, 2)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [11]:
d = np.linspace(0, 10, 5)
print(d)

[  0.    2.5   5.    7.5  10. ]


In [16]:
e = np.empty(5)
print(e)

[ 0.  0.  0.  0.  0.]


In [15]:
f = np.zeros(5)
print(f)

[ 0.  0.  0.  0.  0.]


In [17]:
f2 = np.ones(2)
print(f2)

[ 1.  1.]


In [18]:
g = np.random.rand(5)
print(g)

[ 0.49560444  0.58524296  0.01147289  0.10575494  0.42420421]


In [20]:
g = g * 6 + 1
print(g)
g = g.astype(np.int8)
print(g)

[ 24.84175999  28.06874639   7.41302413  10.80717798  22.27135164]
[24 28  7 10 22]


In [21]:
h = np.arange(1,4)
i = np.arange(4,7)
j = np.concatenate([h,i])
print(j)

[1 2 3 4 5 6]


In [23]:
a = np.array([[1,2,3], [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [24]:
a = np.empty((2,3), dtype=np.int64)

a[0] = [1,2,3]
a[1] = [4,5,6]

print(a)

[[1 2 3]
 [4 5 6]]


In [25]:
a = np.arange(1, 21)
print(a)
print(a.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(20,)


In [26]:
b = a.reshape(4,5)
print(b)
print(b.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
(4, 5)


In [28]:
b2 = a.reshape(2, 2, 5)
print(b2)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [29]:
c = np.arange(1, 21).reshape(4, 5)
d = c.flatten()
print(c)
print(d)

e = c.ravel()

print(c)
print(e)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [30]:
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [43]:
a = np.arange(1,101).reshape(10,10)
print(a[0,0])
print( a[1:3, 1:3])
print(a[1:5:3, 1:5:3])
print(a[1:7:3,:4])
print(a[:,:])

1
[[12 13]
 [22 23]]
[[12 15]
 [42 45]]
[[11 12 13 14]
 [41 42 43 44]]
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [44]:
a = np.arange(1,20)
a = np.append(a, 20)
a = np.append(a, (21, 22, 23, 24))
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [45]:
b = np.arange(1, 6)
b = np.insert(b, 1,6)
b = np.insert(b, 3, (7, 8))
print(b)

[1 6 2 7 8 3 4 5]


In [ ]:
a = np.array([[0,0,0],[0,0,0],[0,0,0]])
b = np.array([1,1,1])

(h, v) = a.shape

c = np.insert(a, 2, b, 0)
print(c)

d = np.insert(a, h, b, 0)
print(d)

e = np.insert(a, 2, b, 1)
print(e)

f = np.insert(a, v, b, 1)
print(f)